let coffeearray=[
    {
        name:"Vanilla latte",
        price:6.99,
        type:"Iced or Hot",
        size: "small, medium, or large",
        milk:"Oat milk, Almond, Dairy, or Soy",
        caffeine:"145",
        rating:"4.7",
        description:"Creamy coffee made with espresso, steamed milk, and sweet vanilla syrup",
        ingredients:["espresso","steamed milk", "vanilla syrup"],
        image:"assets/vanillalatte.webp",
    },
    {
        name:"Hazelnut latte",
        price:6.49,
        type:"Hot or Iced",
        size: "small, medium, or large",
        milk:"Oat milk, Almond, Dairy, or Soy",
        caffeine:"150",
        rating:"4.6",
        description:"Espresso with steamed milk and rich hazelnut flavor",
        ingredients:["espresso","steamed milk","hazelnut syrup"],
        image:"assets/hazelnutlatte.jpg",
    },
    {
        name:"Mocha Latte",
        price: 6.50,
        type:"Hot or Iced",
        size: "small, medium, or large",
        milk:"Oat milk, Almond, Dairy, or Soy",
        caffeine:"140",
        rating:"4.5",
        description:"A chocolatey twist on a classic latte.",
        ingredients:["espresso","steamed milk", "chocolate syrup"],
        image: "assets/mochalatte.jpg",
    },
    {
        name:"Matcha Latte",
        price:7.00,
        type:"Hot or Iced",
        size: "small, medium, or large",
        milk:"Oat milk, Almond, Dairy, or Soy",
        caffeine:"90",
        rating:"4.0",
        description:"Smooth and earthy matcha latte.",
        ingredients:["matcha","steamed milk","sweetener"],
        image: "assets/matchalatte.jpg",
    },
    {
        name:"Strawberry Matcha",
        price:7.50,
        type:"Iced or Hot",
        size: "small, medium, or large",
        milk:"Oat milk, Almond, Dairy, or Soy",
        caffeine:"85",
        rating:"4.3",
        description:"A layered drink with sweet strawberry matcha, and milk.",
        ingredients: ["matcha","strawberry puree", "milk"],
        image:"assets/berrymatcha.jpg"
    }
];
