let coffeearray=[
    {
        name:"Vanilla latte",
        price:6.99,
        type: ["Iced","Hot"],
        size: ["small", "medium", "large"],
        milk:["Oat milk", "Almond", "Dairy", "Soy"],
        caffeine:"145",
        rating:"4.7",
        description:"Creamy coffee made with espresso, steamed milk, and sweet vanilla syrup",
        ingredients: "espresso, steamed milk and vanilla syrup",
        image:"assets/vanillalatte.webp",
    },
    {
        name:"Hazelnut latte",
        price:6.49,
        type: ["Iced","Hot"],
        size: ["small", "medium", "large"],
        milk:["Oat milk", "Almond", "Dairy", "Soy"],
        caffeine:"150",
        rating:"4.6",
        description:"Espresso with steamed milk and rich hazelnut flavor",
        ingredients:"espresso, steamed milk and hazelnut syrup",
        image:"assets/hazelnutlatte.jpg",
    },
    {
        name:"Mocha Latte",
        price: 6.50,
        type: ["Iced","Hot"],
        size: ["small", "medium", "large"],
        milk:["Oat milk", "Almond", "Dairy", "Soy"],
        caffeine:"140",
        rating:"4.5",
        description:"A chocolatey twist on a classic latte",
        ingredients:"espresso, steamed milk and chocolate syrup",
        image: "assets/mochalatte.jpg",
    },
    {
        name:"Matcha Latte",
        price:7.00,
        type: ["Iced","Hot"],
        size: ["small", "medium", "large"],
        milk:["Oat milk", "Almond", "Dairy", "Soy"],
        caffeine:"90",
        rating:"4.0",
        description:"Smooth and earthy matcha latte",
        ingredients:"matcha, steamed milk and sweetener",
        image: "assets/matchalatte.jpg",
    },
    {
        name:"Strawberry Matcha",
        price:7.50,
        type: ["Iced","Hot"],
        size: ["small", "medium", "large"],
        milk:["Oat milk", "Almond", "Dairy", "Soy"],
        caffeine:"85",
        rating:"4.3",
        description:"A layered drink with sweet strawberry matcha, and milk",
        ingredients: "matcha, strawberry puree and milk",
        image:"assets/berrymatcha.jpg",
    },
    {
        name:"House Cold Brew",
        price:4.00,
        type: ["Iced"],
        size: ["small", "medium", "large"],
        milk:["none"],
        caffeine:"200",
        rating:"4.1",
        description:"Smooth, cold brew with deep flavor",
        ingredients:"cold brew coffee",
        image:"assets/coldbrew.jpg",
    },
    {
        name:"Nitro Cold Brew",
        price:4.25,
        type: ["Iced"],
        size: ["small", "medium", "large"],
        milk:["none"],
        caffeine:"250",
        rating:"4.2",
        description:"Cold brew infused with nitrogen for a creamy texture",
        ingredients:"nitro cold brew coffee",
        image:"assets/nitrocoldbrew.webp",
    },
    {
        name:"Espresso",
        price:3.00,
        type: ["Hot"],
        size: ["small"],
        milk:["none"],
        caffeine:"64",
        rating:"5.0",
        description:"Strong and bold coffee served as a single shot",
        ingredients:"espresso",
        image:"assets/espresso.jpg",
    },
    {
        name:"Americano",
        price:3.50,
        type: ["Iced","Hot"],
        size: ["small", "medium", "large"],
        milk:["none"],
        caffeine:"150",
        rating:"4.8",
        description:"Espresso diluated with hot water for a smoother taste",
        ingredients:"espresso and hot water",
        image: "assets/americano.jpg",
    },
    {
        name:"Macchiato",
        price:3.75,
        type: ["Hot"],
        size: ["small", "medium", "large"],
        milk:["Oat milk", "Almond", "Dairy", "Soy"],
        caffeine:"85",
        rating:"3.9",
        description: "Espresso with a dollop of milk foam",
        ingredients:"espresso and milk foam",
        image:"assets/mach.webp",
    },
    {
        name:"Cappuccino",
        price:3.80,
        type: ["Hot"],
        size: ["small", "medium", "large"],
        milk:["Oat milk", "Almond", "Dairy", "Soy"],
        caffeine:"80",
        rating:"3.8",
        description: "Espresso with steamed milk and a thick layer of foam",
        ingredients:"espresso, milk foam and steamed milk",
        image:"assets/capp.webp",
    }
];
